- name: Enable repository
  shell: yum-config-manager --enable remi-php70 
  when: php_version == 70

- name: Enable repository
  shell: yum-config-manager --enable remi-php71 
  when: php_version == 71

- name: Enable repository
  shell: yum-config-manager --enable remi-php72 
  when: php_version == 72

- name: Enable repository
  shell: yum-config-manager --enable remi-php73 
  when: php_version == 73

- name: Enable repository
  shell: yum-config-manager --enable remi-php74 
  when: php_version == 74

- name: Install PHP
  yum:
    name:
      - php
      - php-mysql
    state: latest
    
