- hosts: wordpress
  tasks:
  - name: install httpd
    yum:
      name:
        - httpd
        - wget
      state: present
    notify: restart httpd
  handlers:    
  - name: restart httpd
    service:
      name: httpd
      state: restarted 










