- name: Download wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz

- name: Extract Wordpress
  unarchive:
    src: "{{ folder }}"
    dest: /tmp
    remote_src: yes

- name: Template a file to /var/www/html
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    # remote_src: yes

- name: Copy file with owner and permissions
  copy:
    # trunk-ignore(yamllint/quoted-strings)
    src: "/tmp/wordpress/."
    dest: /var/www/html
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'
    remote_src: yes

- name: Restart Apache
  service: 
    name: httpd
    state: restarted

